unit uProdutoModel;

interface

uses
  MVCFramework.ActiveRecord, System.SysUtils;

type
  [MVCTable('produtos')]
  TProduto = class(TMVCActiveRecord)
  private
    [MVCTableField('id', [foPrimaryKey, foAutoGenerated])]
    FId: Integer;

    [MVCTableField('codigo')]
    FCodigo: string;

    [MVCTableField('nome')]
    FNome: string;

    [MVCTableField('descricao')]
    FDescricao: string;

    [MVCTableField('categoria')]
    FCategoria: string;

    [MVCTableField('unidade_medida')]
    FUnidadeMedida: string;

    [MVCTableField('preco')]
    FPreco: Currency;

    [MVCTableField('estoque')]
    FEstoque: Integer;

    [MVCTableField('ativo')]
    FAtivo: Boolean;

    [MVCTableField('criado_em')]
    FCriadoEm: TDateTime;

    [MVCTableField('atualizado_em')]
    FAtualizadoEm: TDateTime;
  public
    property Id: Integer read FId write FId;
    property Codigo: string read FCodigo write FCodigo;
    property Nome: string read FNome write FNome;
    property Descricao: string read FDescricao write FDescricao;
    property Categoria: string read FCategoria write FCategoria;
    property UnidadeMedida: string read FUnidadeMedida write FUnidadeMedida;
    property Preco: Currency read FPreco write FPreco;
    property Estoque: Integer read FEstoque write FEstoque;
    property Ativo: Boolean read FAtivo write FAtivo;
    property CriadoEm: TDateTime read FCriadoEm write FCriadoEm;
    property AtualizadoEm: TDateTime read FAtualizadoEm write FAtualizadoEm;
  end;

implementation

end.

